---
title: "Jabodetabek Property Market Analysis"
output: 
  flexdashboard::flex_dashboard:
    theme: journal
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(glue)
library(scales)
library(sf)
library(plotly)
library(leaflet)
library(leaflet.extras)

# read data
idn <- st_read(dsn = "shp", layer = "idn")
df <- read.csv("data/listings.csv")

# aggregate
df_agg <- df %>% 
  mutate(
    harga_m2 = harga / m2
  ) %>% 
  group_by(kota, kecamatan) %>% 
  summarise(harga_m2 = median(harga_m2),
            total_listings= n()) %>% 
  ungroup() %>% 
  left_join(idn, by = c("kota" = "NAME_2", "kecamatan" = "NAME_3")) %>% 
  st_as_sf()

```


Disclaimer {.sidebar}
-------------------------------------

**Disclaimer**:  

This dashboard is made for educational purposes only and as a prerequisite for obtaining a certificate from [Algoritma Data Science Academy](https://algorit.ma) as a final project in the DSS Workshop: Building Interactive Maps for Geospatial Analysis in R.

The data displayed is static data from a quick sample of ± 10,000 houses sold on one of the marketplace sites in Indonesia in September 2020. The value displayed does not necessarily represent the actual price.


Column {.tabset}
-------------------------------------

### Prices House by Sub-District

```{r}
pal <- colorNumeric(palette = "Reds", domain = df_agg$harga_m2)

labels <- glue::glue("
  <b>{df_agg$kecamatan}, {df_agg$kota}</b><br>Price: {round(df_agg$harga_m2/1e6, 2)} jt/m2</br>Total Listing: {df_agg$total_listings} Units"
) %>% lapply(htmltools::HTML)

border  <- df_agg %>% 
  filter(NAME_1 == "Jakarta Raya") %>% 
  group_by(NAME_1) %>% 
  summarise() 

leaflet(df_agg) %>% 
  addProviderTiles(providers$CartoDB.Voyager) %>% # using `addProviderTiles()` instead of `addTiles()`
  addPolygons(
    label = labels,
    labelOptions = labelOptions(
      style = list(
        "font-size"="13px",
        "background-color"="white",
        "color"="black"
      )
    ),
    weight = 2,
    color = "white",
    fillOpacity = .8,
    fillColor = ~pal(harga_m2),
     highlight = highlightOptions(
    weight = 5,
    color = "darkred",
    bringToFront = TRUE,
    sendToBack = TRUE,
    opacity = 0.8)
  ) %>% 
  addPolylines(
    data = border,
    color = "darkred",
    opacity = .8,
    weight = 1
  ) %>% 
  addLegend(
    pal = pal,
    values = ~harga_m2,
    opacity = 1,
    title = "Price/m2",
    position = "bottomright"
  ) %>%
  fitBounds(106.686211, -6.370783, 106.972824, -6.089036)
```

### Distribution of Housing Locations

```{r}
perum <- read.csv('data/perumahan.csv')

leaflet(perum) %>% 
  addTiles() %>%
  addCircles(
    label = ~perumahan,
    color = "red"
  ) %>% 
  addHeatmap(
    radius = 9
  ) 
```

Column
-------------------------------------

### Price and Housing Listing Table in the Jabodetabek Area 

```{r}
library(DT)

data <- df_agg %>% 
  as.data.frame() %>% 
  arrange(desc(harga_m2)) %>% 
  select(kota, kecamatan, harga_m2, total_listings) %>% 
  mutate(harga_m2 = number(harga_m2, big.mark = ",")) %>% 
  rename(
    City = kota,
    `Sub-District` = kecamatan,
    `Price/m2` = harga_m2,
    `Total Listing` = total_listings
  ) 

datatable(
  data,
  extensions = "Buttons",
  options = list(
    pageLength = 25,
    dom = 'Bfrtip',
    buttons = c('csv','excel','pdf')
  )
)
```